# Generated by Django 4.1.3 on 2022-12-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenten', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommand',
            new_name='Recommend',
        ),
    ]
