# Generated by Django 4.1.3 on 2022-12-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenten', '0002_rename_recommand_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='img_url',
            new_name='image_link',
        ),
    ]
