# Generated by Django 4.1.3 on 2022-12-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenten', '0003_rename_img_url_recommend_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommend',
            options={'verbose_name_plural': '텐x텐 웹스크래핑'},
        ),
    ]
